### ISSUE TITLE
Public and my Page does not load

### ISSUE THREAD

**Issue by copiis** [jasoncheng/dica#14]
Android 9

**Comment by jasoncheng** [comment]
Beta version?

**Comment by copiis** [comment]
Yes

**Comment by jasoncheng** [comment]
Ok, will look into on this, will take it as urgent issue and install Android 9 emulator for testing

**Comment by jasoncheng** [comment]
issue found!! it's because friendica api response geo tag is object, but i defined in kotlin is type String; in (mawa.link) always return null, so, won't have that issue

![image](https://mawa.link/photo/14212234345be79b4e74dc6494691058-1.png)
![image](https://mawa.link/photo/15218599835be79bcf5a9f8987961252-1.png)

**Comment by jasoncheng** [comment]
@copiis sir, new version should resolve you issue; upload to store for three hours, still not publish yet, will let you know when it done
